### ISSUE TITLE
Lab 1 Feedback

### ISSUE THREAD

**Issue by alanarnholt** [STT3851-Fall2019/lab1-thomaskeener#1]
@thomaskeener 

On line 176 could use the following 

To display the saved file as shown in Figure` \@ref(fig:ig),` use the `include_graphics()` function from `knitr`.^[Use the argument `dpi = 96` inside `include_graphics()`.] 

then make sure to follow your advice in the footnote with:

```{r, label = "ig", echo = FALSE, fig.cap = "Using `knitr::include_graphics()`"}
knitr::include_graphics("./JPG/YourFileName.jpeg", dpi = 96)
```

The rest looks great.

**Comment by thomaskeener** [comment]
@alanarnholt I corrected the image size and reference.  Everything should be correct now.

-Thank You

**Comment by alanarnholt** [comment]
@thomaskeener 

note that the code on line 176 should have backticks around knitr::include_graphics.  The second footnote should be 

To display the saved file as shown in Figure `\@ref(fig:ig)`, use the `include_graphics()` function from knitr.^[Use the argument `dpi = 96` inside `nclude_graphics()`.]

Check your footnotes after doing this....there should be four of them.

**Comment by thomaskeener** [comment]
@alanarnholt 

I think the issues should be resolved now.

**Comment by alanarnholt** [comment]
@thomaskeener looks good!
